#!/bin/bash
mapfile -t words < "list"
declare -A word_count 

for word in "${words[@]}"; do
  ((word_count[$word]++))
done

echo "Unique words:"
for word in "${words[@]}"; do
  if [ ${word_count[$word]} -eq 1 ]; then
    echo "$word"
  fi
done | sort
